### ISSUE TITLE
Possible to replace a one celled table with <p>?

### ISSUE THREAD

**Issue by mwlang** [rgrove/sanitize#132]
I have a lot of HTML fragments where it follows this pattern:

    <TABLE>
      <TR>
        <TD>Some content</TD>
      </TR>
    </TABLE>

Is it possible to easily detect this one row, one cell table and replace with a simple <P> tag like so:

    <P>Some content</P>

**Comment by rgrove** [comment]
Yep, you can do this with a transformer. Just look for a `td` element, and when you find one, look at its parent nodes and count their children. When it's the only child of a `tr` that's the only child of s `table`, delete the `table` and replace it with a `p` containing the contents of the `td`.

**Comment by mwlang** [comment]
Thanks for that tip!  That got me on the right track rapidly.  After re-reading the README and experimenting, I came up with this:

  SINGLE_CELL_TABLE_XFORMER = lambda do |env|
    return unless env[:node_name] == 'table'
    
    table = env[:node]
    thead = table.children.detect{|d| d.name == 'thead'}
    tbody = table.children.detect{|d| d.name == 'tbody'}

    # find the rows, ignore text in between them
    rows = []
    rows += thead.children.select{|s| s.name == 'tr'} if thead
    rows += tbody.children.select{|s| s.name == 'tr'} if tbody
    
    # collect the cells by row
    row_cells = rows.collect{|row| row.children.select{|s| s.name =~ /td|th/}}
    
    # keep the table if any row has 2 or more cells
    return if row_cells.detect{|d| d.size > 1}

    # otherwise, replace the table and rows with paragraphs
    puts '*' * 40, row_cells.flatten.map(&:text).inspect, '*' * 40
    row_cells.flatten.each do |cell|
      p = Nokogiri::XML::Element.new("p", cell.document)
      p.children = cell.children
      table.add_previous_sibling p
    end
    table.unlink
  end
  
  HTML_WHITELIST = Sanitize::Config.merge(
    Sanitize::Config::BASIC,
      elements: Sanitize::Config::BASIC[:elements] + ['table', "tr", "td", "th"],
      attributes: Sanitize::Config::BASIC[:attributes].merge("td" => ['colspan']),
      transformers: [SINGLE_CELL_TABLE_XFORMER]
    )

This will keep any tables with more than one cell on a row, but ditch empty tables and convert single-columned cells into paragraphs.  I found starting at the 'td' level to be costly because the transformer was invoking on every "td" element encountered instead of once at the table level.  Plus, I was having issues "reparenting" when I attempted to replace the table node with a paragraph node.
