### ISSUE TITLE
How to use Sanitize::Config::RELAXED together with transformers

### ISSUE THREAD

**Issue by tfl** [rgrove/sanitize#133]
I have fragments I would like to sanitize. Well, as long as I use it like this

```Sanitize.fragment(<my fragment>, Sanitize::Config::RELAXED)```

all went fine. But what should I do if I like to use your Youtube transformer together with Sanitize::Config::RELAXED? Sanitize.fragment() does not take three arguments.

Thanks in advance

BTW: do you think about including html5 tags like *video* and *audio* into your library?

**Comment by rgrove** [comment]
Howdy!

This section of the readme explains how to copy and customize one of the built-in configs using `Sanitize::Config.merge()`: https://github.com/rgrove/sanitize#custom-configuration

As for `<video>` and `<audio>`, I don't have any immediate plans to add them, but you can easily add them to your custom configuration as described above.

**Comment by tfl** [comment]
Well, I think the keyword ist **:config** as it is not documented how to combine your transformers with your settings - or at least I did not understand it.

```sanitized = { :config => Sanitize::Config::RELAXED, :transformers => [your, sanitizers, here]}```
```Sanitize.fragment(text, sanitized)```

And yes, it works. But I do not know If I open up one or several security wholes doing it this way.

**Comment by rgrove** [comment]
`:transformers` is a key on the same config object as everything else. There is no `:config` key, so in your example the RELAXED config isn't actually being applied, meaning that all elements will be removed unless your transformers allow them.

This is probably what you want:

```ruby
Sanitize.fragment(html, Sanitize::Config.merge(Sanitize::Config::RELAXED,
  :transformers => [
    # Your transformers here.
  ]
))
```

**Comment by tfl** [comment]
Thanks very much
