### ISSUE TITLE
Any way to whitelist url()?

### ISSUE THREAD

**Issue by robophilosopher** [rgrove/sanitize#135]
When I have some inline css like this: 
```<li style="list-style-image: url(http://www.blammo.com/images/bullet.gif);">```
is there a way for me to whitelist url()?

Sorry, if this is the wrong place to ask questions!

**Comment by rgrove** [comment]
Howdy @robophilosopher!

You don't need to whitelist `url()`, but you do need to whitelist the `list-style-image` property ([docs](https://github.com/rgrove/sanitize#css--properties-array-or-set)) and the `http` URL protocol ([docs](https://github.com/rgrove/sanitize#css--protocols-array-or-set)). You can see examples of this in Sanitize's built-in configs, like [this one](https://github.com/rgrove/sanitize/blob/067d58a89363ba9c876093ca618f19a05147cf09/lib/sanitize/config/relaxed.rb#L74-L76).

Hope that helps!

**Comment by robophilosopher** [comment]
Great! Thanks!
