### ISSUE TITLE
Not an issue, just a question about the project.

### ISSUE THREAD

**Issue by ytrezq** [rgrove/sanitize#136]
Sorry for contacting you in this way.
I see you’re doing protocols whitelisting on the`cite=`attribute in`/lib/sanitize/config/basic.rb`. I thought the attribute is purely informative meaning allowing arbitrary ᴜʀɪ is safe.
Or are there really screen readers able to render data: or javascript: ᴜʀɪ with the cite attribute ?

**Comment by rgrove** [comment]
The HTML spec [says](https://html.spec.whatwg.org/multipage/semantics.html#the-blockquote-element):

> If the `cite` attribute is present, it must be a valid URL potentially surrounded by spaces. To obtain the corresponding citation link, the value of the attribute must be resolved relative to the element. User agents may allow users to follow such citation links, but they are primarily intended for private use (e.g. by server-side scripts collecting statistics about a site's use of quotations), not for readers.

This leaves it up to the user agent whether to follow a citation URL or make it navigable. I'm not aware of any browsers that do this, but I want Sanitize to always do the safest thing by default, and in this case the safest thing is to sanitize that URL even if it's unlikely to be necessary.

**Comment by ytrezq** [comment]
Thank you.
