### ISSUE TITLE
Sanitize#fragment attribute whitelist not working

### ISSUE THREAD

**Issue by nicooga** [rgrove/sanitize#138]
~~~ruby
> _body.to_html
=> "<div dir=\"ltr\"><div class=\"gmail_default\" style=\"font-family:monospace,monospace;font-size:small;color:#444444\">\n<a href=\"http://www.google.com\">qwer</a><br>\n</div></div>"
> Sanitize.fragment(_body, elements: %w|a|, attributes: { a: %w|href| })
=> "  \n<a>qwer</a> \n  "
~~~
Maybe I'm misunderstood how this works, or maybe this is broke.
I worked around showing `img` with `src` using a transformer, but I think this defeats the purpose of having an attribute whitelist.

~~~ruby
BODY_TRANSFORMER = -> (env) do
  node = env[:node]

  if node.name == "img"
    node.attributes.each do |attr_name,_|
      node.remove_attribute(attr_name) unless attr_name == "src"
    end

    { node_whitelist: [node] }
  end
end

Sanitize.fragment(body,
  elements: %w|a img br|,
  attributes: {
    a: %w|href|,
    img: %w|src|
  },
  transformers: BODY_TRANSFORMER
)
~~~
Btw, nice gem, has a very simple interface.

**Comment by rgrove** [comment]
Howdy @nicooga. You'll need to whitelist the URL protocols that you want to allow in the `href` and `src` attributes. [This example](https://github.com/rgrove/sanitize#protocols-hash) in the readme demonstrates how to do this for both links and images.

**Comment by nicooga** [comment]
I see, thanks a lot @rgrove! At least there's gonna be a closed issue for people like me who come from google.
