### ISSUE TITLE
Adding support for file urls?

### ISSUE THREAD

**Issue by jhubert** [rgrove/sanitize#143]
hi Ryan,

How do you recommend adding support for file urls? I want to support the following:

```html
<a href="C:\tmp\file name.txt">file</a>
<a href="file:///c:\tmp\file name.txt">file</a>
<a href="file://///network/file name.txt">file</a>
```

I've tried this but it doesn't seem to work:

```
Sanitize::Config.merge(
  Sanitize::Config::RELAXED,
  protocols: {
    'a' => { 'src' => {'href' => ['ftp', 'http', 'https', 'mailto', :relative, 'file']} }
  }
)
```

**Comment by rgrove** [comment]
Looks like you've accidentally nested the `href` protocol list under a `src` property, so it's not being applied. Change it to this if you want to allow `file://` URLs:

```
Sanitize::Config.merge(
  Sanitize::Config::RELAXED,
  protocols: {
    'a' => { 'href' => ['ftp', 'http', 'https', 'mailto', :relative, 'file'] }
  }
)
```

URLs beginning with DOS drive letters aren't technically valid, but if you really want to allow that form, you could also add `c` to the protocol list. You'll need to add each possible drive letter you want to allow though.

Note that I **strongly** recommend not allowing file URLs in user-supplied HTML.

**Comment by jhubert** [comment]
Oops. That was a copy paste error when I made the issue. Sorry.

The bigger answer here was that I have to add each drive letter. That's where I was hitting trouble. Thank you!

**Comment by markedmondson** [comment]
Hey @rgrove, I'm running into the same question/issue. Any ideas?

```ruby
config = Sanitize::Config.merge(
  Sanitize::Config::RELAXED,
  protocols: {
    'a' => { 'href' => ['ftp', 'http', 'https', 'mailto', :relative, 'file'] }
  }
)

html = <<-HTML
  <a href="C:\tmp\file name.txt">file</a>
  <a href="//network/file name.txt">file</a>
  <a href="file:///c:\tmp\file name.txt">file</a>
  <a href="file://///network/file name.txt">file</a>
HTML

Sanitize.fragment(html, config)
```
=>
```
"  <a>file</a>\n" +
"  <a href=\"//network/file%20name.txt\">file</a>\n" +
"  <a href=\"file:///c:%09mpile%20name.txt\">file</a>\n" +
"  <a href=\"file://///network/file%20name.txt\">file</a>\n"
```

**Comment by rgrove** [comment]
@markedmondson Same question, same answer: https://github.com/rgrove/sanitize/issues/143#issuecomment-170721206

> URLs beginning with DOS drive letters aren't technically valid, but if you really want to allow that form, you could also add `c` to the protocol list. You'll need to add each possible drive letter you want to allow though.
