### ISSUE TITLE
Consider adding rel=noopener to <a> sanitization

### ISSUE THREAD

**Issue by typeoneerror** [rgrove/sanitize#146]
Of note: http://mathiasbynens.github.io/rel-noopener/

**Comment by rgrove** [comment]
None of Sanitize's built-in configs allow the `target` attribute on `a` elements. The relaxed config does allow `rel` on `a` elements though, and it can have arbitrary content, so `rel="noopener"` should already be possible with the relaxed config (although I'm not sure what value it has without `target`).

**Comment by typeoneerror** [comment]
@rgrove thanks for your consideration. I've decided to just not let users use target.

**Comment by rgrove** [comment]
Probably a wise choice. If you were looking for a way to automatically add `rel="noopener"` to all `a` elements, that's actually possible too, using the `:add_attributes` config option:

```ruby
:add_attributes => {
  'a' => {'rel' => 'noopener'}
}
```

**Comment by typeoneerror** [comment]
@rgrove yeah, that's what I've done, except w/noreferrer (since noreferrer works with older browsers and is "aliased" as noopener in newer browsers. Thanks again for your time.
