### ISSUE TITLE
How to allow inline data for images

### ISSUE THREAD

**Issue by veelenga** [rgrove/sanitize#149]
Let me thank you first for a great project. This is really cool thing.

Now down to business. Please suggest how to allow [inline data](https://en.wikipedia.org/wiki/Data_URI_scheme) with custom config.

For example, this html
```html
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />
```

with RELAXED config is changed to:

```html
<img alt="Red dot">
```

The main reason of this is to create a config to sanitize html created with [summernote](https://github.com/summernote/summernote). One of it's features is picture uploading, that creates inline data.

**Comment by rgrove** [comment]
You'll need to provide a [custom config](https://github.com/rgrove/sanitize#custom-configuration) that adds 'data' to the [protocol whitelist](https://github.com/rgrove/sanitize#protocols-hash).
