### ISSUE TITLE
Sanitizer.clean transfer "|" into "%7C" automatically.

### ISSUE THREAD

**Issue by tammy-txt** [rgrove/sanitize#152]
I'm using Sanitizer.clean and try to keep the "|" in my url. i.e. Prevent the url escape from transfering "|" to "%7C"

Seems there's no way.

At least is there any configuration could be done to pass in safe character that no need to encode?

**Comment by rgrove** [comment]
The `|` character is defined as an unsafe character by both [RFC 1738](https://www.ietf.org/rfc/rfc1738.txt) and the [WHATWG URL Standard](https://url.spec.whatwg.org/), so it must be encoded.

If you'd prefer not to comply with standards, you can manually replace `%7C` with `|` in your URLs in a post-Sanitize step, but Sanitize itself won't do this for you.
