### ISSUE TITLE
some cases hang & crash Sanitize

### ISSUE THREAD

**Issue by djkz** [rgrove/sanitize#163]
So far i narrowed it down to ending unclosed tag with a newline

`Sanitize.fragment("<http://test/\n",Sanitize::Config::RELAXED)` will hang my process. Similar cases cause seg fault.

**Comment by rgrove** [comment]
I'm not able to reproduce this on macOS with Ruby 2.4.1p111, nokogiri 1.7.2, and nokogumbo 1.4.13. 

Can you please provide more information about your OS and what versions of Ruby, nokogiri, and nokogumbo you're using?

**Comment by djkz** [comment]
Sorry, for some reason didn't get notified of the message:
osX 10.12.6
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
nokogiri (1.8.0) 
nokogumbo (1.4.10)

from rails console:
`
`
`require "sanitize"
Sanitize.fragment("<http://test/\n",Sanitize::Config::RELAXED)
`
Sometimes will hang the process, sometimes will segfaults (from the rails server)

**Comment by rgrove** [comment]
I'm only able to reproduce this with nokogumbo 1.4.10.

I recommend upgrading to nokogumbo 1.4.13, which seems to work fine.
