### ISSUE TITLE
Non-lowercase attributes do not work

### ISSUE THREAD

**Issue by glebm** [rgrove/sanitize#164]
If I try to whitelist `'preserveAspectRatio'` it doesn't work, but it works with `'preserveaspectratio'`. Sanitize v4.5.0.

**Comment by rgrove** [comment]
Attribute and element names in whitelist configs must be specified in lowercase. This is documented at https://github.com/rgrove/sanitize#attributes-hash:

> Specify all element names and attributes in lowercase.

This is mainly to avoid the overhead of having to downcase everything at runtime.
