### ISSUE TITLE
Instead of whitelisting inline css can we remove only the ones that we don't want

### ISSUE THREAD

**Issue by arun-jerry-E0243** [rgrove/sanitize#172]
we have remove content "remove_contents" for removing the html tags right. Can we remove the inline css items in a similar way coz the number css properties that can be whitelisted is more when compared to the ones that needs to be removed so its faster and better right?

Please let me know if my understanding is correct.

**Comment by rgrove** [comment]
No, it's not possible to remove CSS properties based on a blacklist. Sanitize is designed only to support whitelist-based sanitization.
