### ISSUE TITLE
frozen_string_literal roadmap

### ISSUE THREAD

**Issue by janklimo** [rgrove/sanitize#173]
Ryan, thank you for your work on this gem! 

I'd like to ask if `frozen_string_literal` support is on the roadmap? I just ran memory profiler on one of our scripts and saw this:

![screen shot 2018-03-15 at 6 18 36 pm](https://user-images.githubusercontent.com/7811733/37460362-9954b446-287d-11e8-935a-de405d4afb27.png)

Some more details:
![screen shot 2018-03-15 at 6 21 24 pm](https://user-images.githubusercontent.com/7811733/37460459-e02189da-287d-11e8-9cc2-c049da127fb2.png)

I haven't looked into this much and I'm not perfectly sure if `frozen_string_literal` can help in our case, just wanted to open a conversation to see what your thoughts on it are. Thanks!

**Comment by rgrove** [comment]
I'm definitely open to it. I haven't had much free time lately though, so I can't promise I'll be able to get to it soon myself. I'd welcome a PR!

**Comment by flavorjones** [comment]
See PR at #174. Hope it helps!

**Comment by rgrove** [comment]
Awesome! Thanks Mike. 😄 

Merged and released 4.6.1. @janklimo, I'd be interested to hear if running with frozen string literals enabled solves your memory usage issues.

**Comment by janklimo** [comment]
@rgrove I looked into this and I'm afraid this won't help with the way strings are allocated in my example above. The line in question is this one:

https://github.com/rgrove/sanitize/blob/184709be85e06a613311f01e00930010b2cbc6bf/lib/sanitize.rb#L225

I'm not sure if there is a way to optimize the way this keeps allocating lots of identical strings. But those are not string literals, so enabling `frozen_string_literal` makes no difference.

However, it's great to make `sanitize` `frozen_string_literal`-friendly. Thank you @flavorjones lightning-fast response time 🚀👍  Closing.
