### ISSUE TITLE
Serialize to HTML without any formatting to prevent Nokogiri from adding newlines after certain tags

### ISSUE THREAD

**Issue by muthue** [rgrove/sanitize#178]
I have recently upgraded sanitize from "2.0.3" -> "4.5.0" in my application. When doing sanitize.fragment for HTML, it prevents adding newlines from nogokiri which leads to some lines having megabytes size, if I allow this string to sanitize makes high CPU utilization and memory consumption in the machine. 
I tried nokogiri to_html with FORMAT save option before doing sanitize fragment works perfectly.  Could you please advice on this? What is the best way to solve this issue?

**Comment by rgrove** [comment]
Can you please provide some code that demonstrates the issue you're seeing and describe the output you expect to see for a given input?
