### ISSUE TITLE
Allow for Nokogumbo configuration from sanitize_* methods

### ISSUE THREAD

**Issue by maxshortzp** [rgrove/sanitize#192]
**Issue**

I'm using Sanitize on some documents that are deeply nested.

I've gotten the `ArgumentError` `Document tree depth limit exceeded` a few times. To get around this, I've directly overridden `NokoGumbo::DEFAULT_MAX_TREE_DEPTH`. This is obviously not a good coding practice.

**Proposed Fix**

It looks like the options can be passed through `NokoGiri::HTML5.parse` directly so if I'm understanding correctly it would be a small change to lib/sanitize.rb.

I'd be happy to submit a PR if that would helpful.

**Comment by rgrove** [comment]
Take a look at the [`Sanitize#node!`](https://www.rubydoc.info/github/rgrove/sanitize/master/Sanitize:node!) method. You can use Nokogumbo to parse the HTML yourself using whatever options you want, then pass the parsed node to `Sanitize#node!` to sanitize it. This is actually what Sanitize itself does internally.

I think this'll allow you to achieve what you want without needing to modify Sanitize.

**Comment by maxshortzp** [comment]
Thanks for the quick response. That sounds like what we need.
