### ISSUE TITLE
Invalid closing tags added to track and source tags

### ISSUE THREAD

**Issue by sarken** [rgrove/sanitize#196]
When using the `<track>` and `<source>` elements inside an `<audio>` or `<video>` element, closing `</track>` and `</source>` tags are automatically added. 

Example input:
```html
<video>
<source src="some url" type="video/mp4">
<track label="English" kind="subtitles" srclang="en" src="url">
</video>
```

Example output:
```html
<video>
<source src="some url" type="video/mp4"></source>
<track label="English" kind="subtitles" srclang="en" src="url"></track>
</video>
```

However, if you run the resultant code through the W3 Validator, it gives a "Stray end tags" error about `</track>` and `</source>`.  

So the desired output would be: 
```html
<video>
<source src="some url" type="video/mp4">
<track label="English" kind="subtitles" srclang="en" src="url">
</video>
```

We're on Ruby 2.6.5 and Sanitize version 4.6.5, and our [audio and video tag sanitizer is here](https://github.com/otwcode/otwarchive/blob/master/lib/otw_sanitize/media_sanitizer.rb) in case you need to look at our implementation. Running the HTML through nokogiri does not add the closing tags.

**Comment by sarken** [comment]
We tested a more recent version of the gem and that fixed the issue, so I will close this! Apologies for the invalid report and not checking the obvious solution first.

**Comment by rgrove** [comment]
No worries. Glad to hear the newer version solved your problem!
