### ISSUE TITLE
Encoding issue with Sanitize.fragment

### ISSUE THREAD

**Issue by sameeroath** [rgrove/sanitize#197]
Sanitize.clean on below 
```<p>who is the party&rsquo;s</p>```
Changes text to 
```<p>who is the party\u2019s</p>```

How can we keep original htmlentities?

**Comment by rgrove** [comment]
Sorry, Sanitize doesn't preserve unnecessary HTML entities in output.

In HTML, the UTF-8 character `\u2019` is exactly equivalent in meaning to the entity `&rsquo;`. This conversion happens internally in the HTML parser, so Sanitize can't prevent it. If you want certain characters to be represented as unnecessary entities, you'll need to write your own translation step and run it after Sanitize.
