### ISSUE TITLE
`xml` tag being parsed even I didn't include it in my config

### ISSUE THREAD

**Issue by gencer** [rgrove/sanitize#200]
When I receive e-mails from Microsoft (like newsletters), Some of them contains a code like this:

```html
    <!--[if gte (gte mso 9)|(IE)]>
        <xml>
            <o:OfficeDocumentSettings>
            <o:AllowPNG/>
            <o:PixelsPerInch>96</o:PixelsPerInch>
            </o:OfficeDocumentSettings>
        </xml>
    <![endif]-->
        <div>my element </div>
```

Then I sanitize them using fragment:

```ruby
Sanitize.fragment above_html_content, Sanitize::Config::MORE_RELAXED
```
Here is [more_relaxed.rb](https://gist.github.com/gencer/3b57136be7fe4a831e3e173b60e5ecaf)

Sanitize in this case, drops `<xml>` and `if/endif case` however output is not as expected:

## Actual result
```html
       96
<div>my element </div>
```

## Expected Result:

```html
<div>my element </div>
```

Did you see the difference? `96`. Because above code contains: `<o:PixelsPerInch>96</o:PixelsPerInch>` So Sanitize drops everything except `96`. This could be an expected due to HTML principals but I would like to drop `<xml>` completely.

How can I safely avoid XML tags being parsed? I did not include `xml` in my config rules, yet, it is parsed as `96` Can be completely dropped.

**Comment by gencer** [comment]
I am suspecting from this one: https://gist.github.com/gencer/3b57136be7fe4a831e3e173b60e5ecaf#file-more_relaxed-rb-L17

I will test this. Can be this caused by `:all`?

**Comment by rgrove** [comment]
I can't reproduce this with Sanitize 6.0.0 using the built-in relaxed config. If this is still a problem for you, please provide an executable test case that reproduces the problem and I'll take another look.

**Comment by gencer** [comment]
@rgrove Let me try with `v6.x` and if fails again, I'll create reproducible test case for you.
