### ISSUE TITLE
Question: why Sanitize.fragment does not output with html_safe?

### ISSUE THREAD

**Issue by ziemekwolski** [rgrove/sanitize#204]
Sanitize works well and thanks for maintaining it.

I'm wondering why the output is not `html_safe`?
Brakeman complains about needing to use `.html_safe`, hence why I ask.

Thanks

**Comment by rgrove** [comment]
`html_safe` is a Rails feature, but Sanitize is unrelated to Rails and doesn't use or provide any Rails-specific functionality. I'm afraid I'm not familiar with Brakeman.
