### ISSUE TITLE
Why doesn't gem have a support ruby 2.6 in CI?

### ISSUE THREAD

**Issue by randsina** [rgrove/sanitize#214]
Support of ruby 2.6 was deleted since the release 6.0.0
https://github.com/rgrove/sanitize/commit/2539711ea327a4d4a337c49dee5394e173e6bf1f

I run it from the fork for ruby 2.6 and it's green. I found that it really causes a lot of warnings. But ruby 2.5 and 2.7 have the same output with warnings.
https://github.com/randsina/sanitize/runs/3382463209?check_suite_focus=true

Any reason why can't we return it to CI?

**Comment by rgrove** [comment]
I think GitHub Actions was having some odd problems with 2.6 at one point; the failures I was seeing seemed random and were causing builds to be flaky, which is why I disabled it. It seems to be working now though!
