### ISSUE TITLE
CSS gap and row-gap get sanitized, column-gap doesn't

### ISSUE THREAD

**Issue by rmoehn** [rgrove/sanitize#230]
I've found some strange behaviour:

```
require 'sanitize'

Sanitize::CSS.stylesheet(".component { gap: 0; }", Sanitize::Config::RELAXED)
# => ".component {  }"
Sanitize::CSS.stylesheet(".component { row-gap: 0; }", Sanitize::Config::RELAXED)
# => ".component {  }"
Sanitize::CSS.stylesheet(".component { column-gap: 0; }", Sanitize::Config::RELAXED)
# => ".component { column-gap: 0; }"
```

As you can see, with the relaxed config, `gap` and `row-gap` get removed, `column-gap` doesn't. I would expect that none of them get removed. Or am I overlooking some way they could be abused?

**Comment by rgrove** [comment]
Hi! There's nothing unsafe about `gap` and `row-gap`. They're just newer than `column-gap` and haven't made it into the relaxed allowlist yet. If you need to use these properties, you can use a [custom config](https://github.com/rgrove/sanitize#custom-configuration).

**Comment by rmoehn** [comment]
Okay, thank you! We'll do that.
