### ISSUE TITLE
Formatting of html document is not well preserved

### ISSUE THREAD

**Issue by max-las** [rgrove/sanitize#234]
Sanitize seems to break formatting around elements such as `html`, `head` and `body`.

Most obvious example would be [the one in the readme](https://github.com/rgrove/sanitize?tab=readme-ov-file#html-documents) :
```
html = %[
  <!DOCTYPE html>
  <html>
    <b><a href="http://foo.com/">foo</a></b><img src="bar.jpg">
  </html>
]

Sanitize.document(html,
  :allow_doctype => true,
  :elements      => ['html']
)
```
actually returns
```
<!DOCTYPE html><html>foo
  
</html>
```
instead of alleged
```
<!DOCTYPE html>
<html>foo

</html>
```

Here's a more complete example :
```
html = <<~HTML.chomp
  <!DOCTYPE html>
  <html>
    <head>
      <meta charset="UTF-8">
    </head>
    <body>
      <p>Hello</p>
    </body>
  </html>
HTML

Sanitize.document(html,
  allow_doctype: true,
  elements: %w[html head meta body p],
  attributes: { 'meta' => %w[charset] }
)
```
returns
```
<!DOCTYPE html><html><head>
    <meta charset="UTF-8">
  </head>
  <body>
    <p>Hello</p>
  
</body></html>
```

**Comment by rgrove** [comment]
Thanks for pointing this out!

Sanitize doesn't claim to be able to preserve formatting, but I agree it's awkward that the example output in the readme no longer matches the actual output.

**Comment by flavorjones** [comment]
I've opened #234 to fix the formatting in the README.
