### ISSUE TITLE
How to whitelist &

### ISSUE THREAD

**Issue by bhellman1** [rgrove/sanitize#48]
If you submit a field with "hello & world" sanitize is saving that in the DB as:

```
hello &amp; world 
```

How can you whitelist the & . We want sanitize to remove all possible malicious html and JS/script tags. but we're ok allowing the ampersand.

I tried but that had no effect:

```
Sanitize.clean(self[column.name], :elements => %w[&])
```

Thanks

**Comment by joerodrig3** [comment]
Thank you @amseledka
